INSERT OR REPLACE INTO defaultWOD (name, type, description) VALUES
                                                  ('ABBATE', 'For Time', 'Run 1.6 km, 21 Clean and Jerks (70 kg), Run 800 m, 21 Clean and Jerks (70 kg), Run 1.6 km'),
                                                  ('ADAMBROWN', 'For Time', '2 Rounds: 24 Deadlifts (134 kg), 24 Box Jumps (61 cm), 24 Wall Ball Shots (9 kg), 24 Bench Presses (88 kg), 24 Box Jumps (61 cm), 24 Wall Ball Shots (9 kg), 24 Cleans (66 kg)'),
                                                  ('ADRIAN', 'For Time', '7 Rounds: 3 Forward Rolls, 5 Wall Climbs, 7 Toes-to-Bar, 9 Box Jumps (76 cm)'),
                                                  ('ARNIE', 'For Time', 'With a single 32 kg kettlebell: 21 Turkish Get-Ups (Right Arm), 50 Swings, 21 Overhead Squats (Left Arm), 50 Swings, 21 Overhead Squats (Right Arm), 50 Swings, 21 Turkish Get-Ups (Left Arm)'),
                                                  ('BADGER', 'For Time', '3 Rounds: 30 Squat Cleans (43 kg), 30 Pull-Ups, Run 800 m'),
                                                  ('BARAZZA', 'AMRAP 18 Minutes', 'Run 200 m, 9 Deadlifts (125 kg), 6 Burpee Bar Muscle-Ups'),
                                                  ('BELL', 'For Time', '3 Rounds: 21 Deadlifts (84 kg), 15 Pull-Ups, 9 Front Squats (84 kg)'),
                                                  ('BIG SEXY', 'For Time', '5 Rounds: 6 Deadlifts (143 kg), 6 Burpees, 5 Cleans (102 kg), 5 Chest-to-Bar Pull-Ups, 4 Thrusters (70 kg), 4 Muscle-Ups'),
                                                  ('BLAKE', 'For Time', '4 Rounds: 30 m Walking Lunge with 20 kg plate held overhead, 30 Box Jumps (61 cm), 20 Wall Ball Shots (9 kg), 10 Handstand Push-Ups'),
                                                  ('BOWEN', 'For Time', '3 Rounds: Run 800 m, 7 Deadlifts (125 kg), 10 Burpee Pull-Ups, 14 Single-Arm Kettlebell Thrusters (24 kg, 7 each arm), 20 Box Jumps (61 cm)'),
                                                  ('BRADLEY', 'For Time', '10 Rounds: Sprint 100 m, 10 Pull-Ups, Sprint 100 m, 10 Burpees; Rest 30 seconds'),
                                                  ('BRADSHAW', 'For Time', '10 Rounds: 3 Handstand Push-Ups, 6 Deadlifts (102 kg), 12 Pull-Ups, 24 Double-Unders'),
                                                  ('BREHM', 'For Time', '10 Rope Climbs (4.5 m), 20 Back Squats (102 kg), 30 Handstand Push-Ups, Row 40 Calories'),
                                                  ('BRENTON', 'For Time', '5 Rounds: 30 m Bear Crawl, 30 m Standing Broad-Jump; Do 3 Burpees after every 5 Broad-Jumps. If you have a 9 kg vest or body armor, wear it.'),
                                                  ('BULL', 'For Time', '2 Rounds: Run 1.6 km, 50 Pull-Ups, 100 Push-Ups, 150 Squats; Wear a 9 kg vest if you have one.'),
                                                  ('CAL', 'For Time', 'Run 800 m with a 9 kg medicine ball, 80 Squats with medicine ball, 60 Sit-Ups with medicine ball, 40 Push-Ups with medicine ball, Run 800 m with medicine ball'),
                                                  ('CARSE', 'For Time', '21-18-15-12-9-6-3 reps: Squat Clean (43 kg), Double-Under, Deadlift (70 kg), Box Jump (61 cm); Begin each round with a 50 m Bear Crawl.'),
                                                  ('CHAD', 'For Time', '1,000 Box Step-Ups (51 cm) with a 20 kg rucksack'),
                                                  ('CHESTER', 'For Time', '1-2-3-4-5-6-7-8-9-10 reps: Clean (61 kg), Strict Handstand Push-Up'),
                                                  ('CHRIS', 'For Time', '5 Rounds: 15 GHD Sit-Ups, 15 Back Extensions, 15 Knees-to-Elbows, 15 Toes-to-Bar'),
                                                  ('CLARK', 'For Time', '3 Rounds: 155 Squats, 10 Meter Hill Sprint (20 m elevation), 10 Rope Climbs (4.5 m)'),
                                                  ('CLIFFORD', 'For Time', '6 Rounds: 3 Deadlifts (143 kg), 3 Rope Climbs (4.5 m), 3 Handstand Push-Ups; If you have a 9 kg vest or body armor, wear it.'),
                                                  ('CLOVIS', 'For Time', 'Run 16 km, 150 Burpee Pull-Ups; Partition the run and burpee pull-ups as needed. If you have a 9 kg vest or body armor, wear it.'),
                                                  ('COE', 'For Time', '10 Rounds: 10 Thrusters (43 kg), 10 Ring Push-Ups'),
                                                  ('COLLIN', 'For Time', '6 Rounds: Carry 22.5 kg dumbbells 180 m, 50 Push-Ups, Carry 22.5 kg dumbbells 180 m, 50 Squats; If you have a 9 kg vest or body armor, wear it.'),
                                                  ('COLOMBIA', 'For Time', '5 Rounds: 800 m Run, 200 m Dumbbell Farmers Carry (22.5 kg), 50 Push-Ups'),
                                                  ('COOPER', 'For Time', '10 Rounds: 10 Burpees, 10 Squats, 10 Push-Ups; Rest 2 minutes between rounds.'),
                                                  ('CROCKETT', 'For Time', '10-9-8-7-6-5-4-3-2-1 reps: Squat Clean (70 kg), Double-Under, Deadlift (102 kg), Box Jump (61 cm); Begin each round with a 50 m Bear Crawl.'),
                                                  ('CURTIS P', 'For Time', '100 reps of: 1 Power Clean (43 kg), 1 Lunge (Left Leg), 1 Lunge (Right Leg), 1 Push Press'),
                                                  ('DANNY', 'AMRAP 20 Minutes', '30 Box Jumps (61 cm), 20 Push Presses (53kg/35kg), 30 pull ups'),
                                                  ('DANIEL', 'For Time', '50 Pull-Ups, 400 meter Run, 21 Thrusters (43 kg), 800 meter Run, 21 Thrusters (43 kg), 400 meter Run, 50 Pull-Ups'),
                                                  ('DEL', 'For Time', '25 Burpees, Run 400 meters with a 20 kg plate, 25 Weighted Pull-Ups with a 20 kg plate, Run 400 meters with a 20 kg plate, 25 Handstand Push-Ups'),
                                                  ('DEMETRI', 'For Time', '21-15-9 reps: Deadlifts (102 kg), Box Jumps (61 cm), Clean-and-Jerks (61 kg)'),
                                                  ('DGB', 'For Time', '8 Rounds: 200 meter Run, 10 meter Rope Climb, 1 Muscle-Up'),
                                                  ('DONNY', 'For Time', '21-15-9-9-15-21 reps: Deadlifts (102 kg), Burpees'),
                                                  ('DORK', 'For Time', '6 Rounds: 60 Double-Unders, 30 Kettlebell Swings (24 kg), 15 Burpees'),
                                                  ('DT', 'For Time', '5 Rounds: 12 Deadlifts (70 kg), 9 Hang Power Cleans (70 kg), 6 Push Jerks (70 kg)'),
                                                  ('DUNN', 'For Time', '3 Rounds: 15 Muscle-Ups, 7 Push Jerks (84 kg), 1000 meter Run'),
                                                  ('EVA', 'For Time', '5 Rounds: 800 meter Run, 30 Kettlebell Swings (32 kg), 30 Pull-Ups'),
                                                  ('FALKEL', 'For Time', '8 Rounds: 200 meter Run, 2 Rope Climbs'),
                                                  ('FELIX', 'For Time', '21-15-9 reps: Deadlifts (102 kg), Box Jumps (61 cm), Clean-and-Jerks (61 kg)'),
                                                  ('FIGHT GONE BAD', '3 Rounds', '1 minute Wall Balls (9 kg), 1 minute Sumo Deadlift High-Pulls (35 kg), 1 minute Box Jumps (61 cm), 1 minute Push Presses (35 kg), 1 minute Row (calories), 1 minute Rest'),
                                                  ('FILTHY 50', 'For Time', '50 Box Jumps (61 cm), 50 Jumping Pull-Ups, 50 Kettlebell Swings (16 kg), 50 Walking Lunges, 50 Knees-to-Elbows, 50 Push Presses (20 kg), 50 Back Extensions, 50 Wall Ball Shots (9 kg), 50 Burpees, 50 Double-Unders'),
                                                  ('FORREST', 'For Time', '3 Rounds: 20 L-Pull-Ups, 30 Toes-to-Bar, 40 Burpees, 800 meter Run'),
                                                  ('FRANTZ', 'For Time', '21-15-9 reps: Thrusters (43 kg), Pull-Ups'),
                                                  ('FRELEN', 'For Time', '5 Rounds: Run 800 meters, 15 Dumbbell Thrusters (22.5 kg), 15 Pull-Ups'),
                                                  ('GALLANT', 'For Time', 'For Time: 1 mile Run, 60 Burpee Pull-Ups'),
                                                  ('GARRETT', 'For Time', '3 Rounds: 800 meter Run, 21 L-Pull-Ups'),
                                                  ('GATOR', 'For Time', '8 Rounds: 5 Front Squats (84 kg), 26 Ring Push-Ups'),
                                                  ('GLEN', 'For Time', '30 Clean-and-Jerks (61 kg), 1 mile Run, 10 Rope Climbs, 1 mile Run, 100 Burpees'),
                                                  ('GRIFF', 'For Time', 'Run 800 meters, Run 400 meters backwards, Run 800 meters, Run 400 meters backwards'),
                                                  ('GRIFFIN', 'For Time', '800 meter Run, 400 meter Run, 800 meter Run, 400 meter Run'),
                                                  ('HAMMER', '5 Rounds', '5 Power Cleans (61 kg), 10 Front Squats (61 kg), 5 Jerks (61 kg), 20 Pull-Ups'),
                                                  ('HAMMERTIME', 'For Time', '5 Rounds: 5 Deadlifts (102 kg), 10 Toes-to-Bar, 15 Kettlebell Swings (24 kg)'),
                                                  ('HANNAH', 'For Time', '3 Rounds: 800 meter Run, 21 Kettlebell Swings (24 kg), 12 Pull-Ups'),
                                                  ('HANSEN', 'For Time', '5 Rounds: 30 Kettlebell Swings (32 kg), 30 Burpees, 30 GHD Sit-Ups'),
                                                  ('HARD CINDY', 'AMRAP 20 Minutes', '5 Pull-Ups, 10 Push-Ups, 15 Air Squats'),
                                                  ('HAWK', 'For Time', 'AMRAP in 3 minutes: 5 Deadlifts (102 kg), 10 Kettlebell Swings (32 kg), 15 Box Jumps (61 cm)'),
                                                  ('HEATHER', 'For Time', '3 Rounds: 200 meter Run, 12 Chest-to-Bar Pull-Ups, 21 Walking Lunges'),
                                                  ('HELEN', 'For Time', '3 Rounds: 400 meter Run, 21 Kettlebell Swings (24 kg), 12 Pull-Ups'),
                                                  ('HILDY', 'For Time', '100 Calorie Row, 75 Thrusters (20 kg), 50 Pull-Ups, 25 Handstand Push-Ups'),
                                                  ('HOLLEYMAN', 'For Time', '30 Rounds: 5 Wall Balls (9 kg), 3 Handstand Push-Ups, 1 Power Clean (84 kg)'),
                                                  ('HOLLYMAN', 'For Time', '30 Rounds: 5 Wall Balls (9 kg), 3 Handstand Push-Ups, 1 Power Clean (84 kg)'),
                                                  ('HORVATH', 'For Time', '2 Rounds: 5 Wall Climbs, 10 Toes-to-Bar, 50 ft. Overhead Walking Lunge (61 kg), 100 ft. Sprint'),
                                                  ('HOTSHOTS 19', '6 Rounds', '30 Air Squats, 19 Power Cleans (61 kg), 7 Strict Pull-Ups, 400 meter Run'),
                                                  ('HULK', 'For Time', '5 Rounds: 5 Power Cleans (102 kg), 5 Front Squats (102 kg), 5 Jerks (102 kg), 3 Muscle-Ups'),
                                                  ('HUMBERTO', 'For Time', '21-15-9 reps: Overhead Squats (43 kg), Bench Presses (bodyweight)'),
                                                  ('JACK', 'AMRAP 20 Minutes', '10 Push Presses (52 kg), 10 Kettlebell Swings (24 kg), 10 Box Jumps (61 cm)'),
                                                  ('JAMES', 'For Time', '5 Rounds: 200 meter Run, 11 Thrusters (61 kg), 200 meter Run, 11 Pull-Ups'),
                                                  ('JASON', 'For Time', '100 Squats, 5 Muscle-Ups, 75 Squats, 10 Muscle-Ups, 50 Squats, 15 Muscle-Ups, 25 Squats, 20 Muscle-Ups'),
                                                  ('JENNY', 'AMRAP 20 Minutes', '20 Overhead Squats (43 kg), 20 Back Squats (43 kg), 400 meter Run'),
                                                  ('JERRY', 'For Time', 'Run 1 mile, 2,000 meter Row, 1 mile Run'),
                                                  ('JESSE', 'For Time', '3 Rounds: 1 minute Handstand Hold, 100 ft. Walking Lunge, 100 ft. Bear Crawl'),
                                                  ('JESSICA', 'For Time', 'For Time: 800 meter Run, 21 Deadlifts (102 kg), 21 Handstand Push-Ups, 800 meter Run, 15 Deadlifts (102 kg), 15 Handstand Push-Ups, 800 meter Run, 9 Deadlifts (102 kg), 9 Handstand Push-Ups'),
                                                  ('JOSH', 'For Time', '21 Overhead Squats (43 kg), 42 Pull-Ups, 15 Overhead Squats (43 kg), 30 Pull-Ups, 9 Overhead Squats (43 kg), 18 Pull-Ups'),
                                                  ('JOSHIE', 'For Time', '3 Rounds: 21 Kettlebell Swings (24 kg), 21 Pull-Ups, 800 meter Run'),
                                                  ('JT', '21-15-9 reps', 'Handstand Push-Ups, Ring Dips, Push-Ups'),
                                                  ('JUMBO', 'For Time', '5 Rounds: 30 Wall Balls (9 kg), 30 Box Jumps (61 cm), 30 Kettlebell Swings (24 kg)'),
                                                  ('KALI', 'For Time', '4 Rounds: 100 ft. Walking Lunge, 30 Sit-Ups, 20 Pull-Ups, 10 Handstand Push-Ups'),
                                                  ('KAREN', 'For Time', '150 Wall Balls (9 kg)'),
                                                  ('KELLY', 'For Time', '5 Rounds: 400 meter Run, 30 Box Jumps (61 cm), 30 Wall Balls (9 kg)'),
                                                  ('KLEPTO', '4 Rounds', '27 Box Jumps (61 cm), 20 Burpees, 11 Squat Cleans (61 kg)'),
                                                  ('KYLE', 'For Time', '3 Rounds: 40 Overhead Walking Lunges (20 kg), 30 Box Jumps (61 cm), 20 Wall Balls (9 kg), 10 Handstand Push-Ups'),
                                                  ('LUMBERJACK 20', 'For Time', '20 Deadlifts (125 kg), Run 400 meters, 20 Kettlebell Swings (32 kg), Run 400 meters, 20 Overhead Squats (61 kg), Run 400 meters, 20 Burpees, Run 400 meters, 20 Chest-to-Bar Pull-Ups, Run 400 meters, 20 Box Jumps (61 cm), Run 400 meters, 20 Dumbbell Squat Cleans (22.5 kg), Run 400 meters'),
                                                  ('LUMBERJACK 9', 'For Time', '9 Rounds: 11 Power Cleans (84 kg), 100 meter Sprint, 12 Pull-Ups'),
                                                  ('LYNNE', '5 Rounds', 'Max Reps Bench Press (bodyweight), Max Reps Pull-Ups'),
                                                  ('MAGGIE', 'For Time', '5 Rounds: 20 Handstand Push-Ups, 40 Pull-Ups, 60 Pistols'),
                                                  ('MANION', '7 Rounds', 'Run 400 meters, 29 Back Squats (61 kg)'),
                                                  ('MANNING', 'For Time', '50-40-30-20-10 reps: Double-Unders, Sit-Ups, Pull-Ups, Push-Ups'),
                                                  ('MARGUERITA', 'For Time', '50 reps: Burpee/Push-Up/Jumping-Jack/Sit-Up/Handstand'),
                                                  ('MARY', 'AMRAP 20 Minutes', '5 Handstand Push-Ups, 10 Pistols (alternating legs), 15 Pull-Ups'),
                                                  ('MATT 19', 'For Time', '3 Rounds: 400 meter Run, 19 Deadlifts (102 kg), 19 Kettlebell Swings (24 kg)'),
                                                  ('MATTY G', 'For Time', '26 Rounds: 5 Pull-Ups, 10 Push-Ups, 15 Air Squats'),
                                                  ('McGHEE', 'For Time', '30 minute AMRAP: 5 Deadlifts (125 kg), 13 Push-Ups, 9 Box Jumps (61 cm)'),
                                                  ('MCKEOWN', 'For Time', '4 Rounds: 400 meter Run, 16 Kettlebell Swings (24 kg), 12 Pull-Ups'),
                                                  ('MACHO BEAR', 'For Time', '5 Rounds: 3 Power Cleans (84 kg), 3 Front Squats (84 kg), 3 Jerks (84 kg); Rest 3 minutes between rounds.'),
                                                  ('MANNY', 'For Time', '5 Rounds: 400 m Run, 13 Toes-to-Bar, 13 Deadlifts (102 kg), 13 Burpees Over the Bar'),
                                                  ('MARTIN', 'For Time', '3 Rounds: 800 m Run, 20 Pull-Ups, 30 Kettlebell Swings (24 kg), 40 Air Squats'),
                                                  ('MATTHEW', 'For Time', '4 Rounds: 400 m Run, 15 Bench Presses (70 kg), 15 Back Squats (70 kg)'),
                                                  ('MCCLAIN', 'For Time', '4 Rounds: 9 Front Squats (84 kg), 15 Kettlebell Swings (32 kg), 21 Box Jumps (61 cm)'),
                                                  ('MORRISON', 'For Time', '50-40-30-20-10 reps: Wall Ball Shots (9 kg), Box Jumps (61 cm), Kettlebell Swings (24 kg)'),
                                                  ('NATE', 'AMRAP 20 Minutes', '2 Muscle-Ups, 4 Handstand Push-Ups, 8 Kettlebell Swings (32 kg)'),
                                                  ('NED', 'For Time', '7 Rounds: 11 Back Squats (102 kg), 1,000 m Row'),
                                                  ('NUTTS', 'For Time', '10 Handstand Push-Ups, 15 Deadlifts (113 kg), 25 Box Jumps (76 cm), 50 Pull-Ups, 100 Wall Ball Shots (9 kg), 400 m Run with 20 kg plate'),
                                                  ('PAUL', 'For Time', '5 Rounds: 50 Double-Unders, 35 Knees-to-Elbows, 20 Yard Overhead Walk (43 kg barbell)'),
                                                  ('RANDY', 'For Time', '75 Power Snatches (34 kg)'),
                                                  ('RILEY', 'For Time', '1.5 mile Run, 150 Burpees, 1.5 mile Run; Wear a 9 kg weight vest if available.'),
                                                  ('RJ', '5 Rounds for Time', '800 m Run, 5 Rope Climbs (4.5 m), 50 Push-Ups'),
                                                  ('RORY', 'AMRAP 20 Minutes', '20 Thrusters (43 kg), 20 Alternating Single-Leg Squats, 20 Ring Dips'),
                                                  ('RYAN', '5 Rounds for Time', '7 Muscle-Ups, 21 Burpees; Each burpee terminates with a jump one foot above max standing reach.'),
                                                  ('STEPHEN', '30-25-20-15-10-5 reps for Time', 'GHD Sit-Ups, Back Extensions, Knees-to-Elbows, Sit-Ups'),
                                                  ('TOM', '7 Rounds for Time', '7 Muscle-Ups, 11 Thrusters (52 kg), 14 Toes-to-Bar'),
                                                  ('TYLER', '5 Rounds for Time', '7 Muscle-Ups, 21 Sumo Deadlift High-Pulls (43 kg)'),
                                                  ('WILMOT', '6 Rounds for Time', '50 Air Squats, 25 Ring Dips, 400 m Run'),
                                                  ('WOOD', '5 Rounds for Time', '400 m Run, 10 Burpee Box Jumps (61 cm), 10 Sumo Deadlift High-Pulls (43 kg), 10 Thrusters (43 kg), Rest 1 minute'),
                                                  ('WOODROW', 'For Time', '5 Rounds: 400 m Run, 10 Burpee Box Jumps (61 cm), 10 Sumo Deadlift High-Pulls (43 kg), 10 Thrusters (43 kg), Rest 1 minute'),
                                                  ('WITTMAN', '7 Rounds', '15 Kettlebell Swings (24 kg), 15 Power Cleans (43 kg), 15 Box Jumps (61 cm)'),
                                                  ('ZACH', 'For Time', '6 Rounds: 6 Squat Snatches (70 kg), 11 Pull-Ups, 6 Thrusters (70 kg), 11 Toes-to-Bar'),
                                                  ('ZEMAN', 'For Time', '5 Rounds: 400 m Run, 30 Wall Balls (9 kg), 30 Sumo Deadlift High-Pulls (43 kg)'),
                                                  ('ZIMMERMAN', 'AMRAP 25 Minutes', '11 Chest-to-Bar Pull-Ups, 2 Deadlifts (143 kg), 10 Handstand Push-Ups'),
                                                  ('STEPHEN', '30-25-20-15-10-5 reps for Time', 'GHD Sit-Ups, Back Extensions, Knees-to-Elbows, Sit-Ups'),
                                                  ('SANTIAGO', 'For Time', '7 Rounds: 18 Dumbbell Hang Squat Cleans (22.5 kg each), 18 Pull-Ups, 10 Power Cleans (61 kg), 10 Handstand Push-Ups'),
                                                  ('SEVERIN', 'For Time', '50 Strict Pull-Ups, 100 Hand-Release Push-Ups, 5 km Run; Wear a 9 kg vest if available.'),
                                                  ('SHAM', 'For Time', '7 Rounds: 11 Bodyweight Deadlifts, 100-meter Sprint; Rest 2 minutes between rounds'),
                                                  ('SHIP', 'For Time', '9 Rounds: 7 Squat Cleans (84 kg), 8 Burpee Box Jumps (61 cm)'),
                                                  ('SIMPSON', 'AMRAP 20 Minutes', '5 Parallette Handstand Push-Ups, 10 Toes-to-Bar'),
                                                  ('SMALL', 'For Time', '3 Rounds: 1,000-meter Row, 50 Burpees, 50 Box Jumps (61 cm), 800-meter Run'),
                                                  ('SPEHAR', 'For Time', '100 Thrusters (20 kg), 100 Pull-Ups, 800-meter Weighted Run (20 kg), 100 Handstand Push-Ups, 100 Kettlebell Swings (24 kg), 800-meter Weighted Run (20 kg)'),
                                                  ('STONE', 'For Time', '5 Rounds: 30 Push-Ups, 30 Ring Dips, 15-foot Rope Climb, 400-meter Run'),
                                                  ('SWARTZ', 'For Time', '5 Rounds: 5 Burpees, 10 Pull-Ups, 20 Push-Ups, 30 Sit-Ups, 400-meter Run'),
                                                  ('ZOEY', 'For Time', '3 Rounds: 30 Wall Balls (9 kg), 30 Sumo Deadlift High-Pulls (43 kg), 30 Box Jumps (61 cm)'),
                                                  ('TERRY', 'For Time', '1-mile Run, 100 Push-Ups, 100-meter Bear Crawl, 1-mile Run, 100-meter Bear Crawl, 100 Push-Ups, 1-mile Run'),
                                                  ('THOMPSON', 'For Time', '10 Rounds: 1 Rope Climb (4.5 m), 29 Back Squats (61 kg), 10-meter Barbell Farmer Carry (61 kg each hand)'),
                                                  ('TILLMAN', '7 Rounds for Time', '7 Deadlifts (143 kg), 200-meter Sprint, 15 Pull-Ups, 45-second Rest'),
                                                  ('TK', 'AMRAP 20 Minutes', '8 Strict Pull-Ups, 8 Box Jumps (76 cm), 12 Kettlebell Swings (32 kg)'),
                                                  ('TOMMY MAC', 'For Time', '12 Burpees, 12 Thrusters (61 kg), 12 Burpees, 12 Power Snatches (61 kg), 12 Burpees, 12 Push Jerks (61 kg), 12 Burpees, 12 Hang Squat Cleans (61 kg), 12 Burpees, 12 Overhead Squats (61 kg)'),
                                                  ('TREVOR', 'For Time (Team of Four)', '300 Pull-Ups, 400 Push-Ups, 500 Sit-Ups, 600 Air Squats; Only two athletes can work at a time.'),
                                                  ('TULLY', '4 Rounds for Time', '200-meter Swim, 23 Wall Ball Shots (9 kg), 23 Kettlebell Swings (24 kg), 23 Pull-Ups, 23 Burpees'),
                                                  ('TUMILSON', '8 Rounds for Time', 'Run 200 meters, 11 Dumbbell Burpee Deadlifts (22.5 kg each)'),
                                                  ('TYLER', '5 Rounds for Time', '7 Muscle-Ups, 21 Sumo Deadlift High-Pulls (43 kg)'),
                                                  ('RAGNA', 'For Time', '5 Rounds: 400-meter Run, 15 Overhead Squats (43 kg), 15 Pull-Ups'),
                                                  ('RAY', 'For Time', '5 Rounds: 225-meter Run, 15 Push-Ups, 15 Overhead Squats (43 kg)'),
                                                  ('RICK', 'For Time', '10 Rounds: 10 Deadlifts (102 kg), 20 Push-Ups, 30 Box Jumps (61 cm)'),
                                                  ('ROBERT', 'For Time', '6 Rounds: 20 Pull-Ups, 40 Push-Ups, 60 Squats, 800-meter Run'),
                                                  ('ROBIN', 'For Time', '4 Rounds: 400-meter Run, 20 Burpees, 20 Kettlebell Swings (24 kg)'),
                                                  ('ROCKY', 'For Time', '3 Rounds: 800-meter Run, 30 Kettlebell Swings (24 kg), 30 Box Jumps (61 cm)'),
                                                  ('ROGERS', 'For Time', '5 Rounds: 400-meter Run, 15 Deadlifts (102 kg), 15 Pull-Ups'),
                                                  ('ROSE', 'For Time', '4 Rounds: 400-meter Run, 20 Thrusters (43 kg), 20 Pull-Ups'),
                                                  ('RUDY', 'For Time', '5 Rounds: 400-meter Run, 15 Power Cleans (61 kg), 15 Pull-Ups'),
                                                    ('RYAN', '5 Rounds for Time', '7 Muscle-Ups, 21 Burpees; Each burpee terminates with a jump one foot above max standing reach.'),
                                                    ('SAGE', 'For Time', '20 Thrusters (43 kg), 20 Pull-Ups, 20 Power Cleans (61 kg), 20 Pull-Ups, 20 Overhead Squats (43 kg), 20 Pull-Ups'),
                                                    ('SANTORA', '3 Rounds for Time', '155 Squats, 50 Push-Ups, 155 Walking Lunges, 50 Push-Ups'),
                                                    ('SCOTT', 'For Time', '11 Push Presses (52 kg), 50 Double-Unders, 11 Thrusters (52 kg), 50 Double-Unders, 11 Push Presses (52 kg), 50 Double-Unders, 11 Thrusters (52 kg), 50 Double-Unders'),
                                                    ('SEAN', '10 Rounds for Time', '11 Chest-to-Bar Pull-Ups, 2 Deadlifts (143 kg), 10 Handstand Push-Ups'),
                                                    ('SHAWN', 'For Time', '5 Rounds: 200-meter Run, 11 Bodyweight Back Squats'),
                                                    ('SHAY', 'For Time', '5 Rounds: 200-meter Run, 15 Chest-to-Bar Pull-Ups'),
                                                    ('SHIVAN', 'For Time', '4 Rounds: 400-meter Run, 15 Deadlifts (102 kg), 15 Pull-Ups'),
                                                    ('SMITH', 'For Time', '6 Rounds: 200-meter Run, 3 Deadlifts (143 kg), 10 Toes-to-Bar'),
                                                    ('SPEEDY', 'For Time', '5 Rounds: 200-meter Run, 9 Power Cleans (61 kg), 9 Burpees'),
                                                    ('SPENCER', 'For Time', '10 Rounds: 100-meter Sprint, 10 Burpees'),
                                                    ('STEWART', 'For Time', '5 Rounds: 200-meter Run, 11 Push-Ups, 11 Box Jumps (61 cm)'),
                                                    ('STONER', 'For Time', '5 Rounds: 200-meter Run, 10 Push-Ups, 10 Squat Cleans (61 kg)'),
                                                    ('STOUT', 'For Time', '5 Rounds: 200-meter Run, 15 Kettlebell Swings (24 kg), 15 Pull-Ups'),
                                                    ('TAYLOR', '4 Rounds for Time', '400-meter Run, 5 Burpee Muscle-Ups'),
                                                    ('TOM', '7 Rounds for Time', '7 Muscle-Ups, 11 Thrusters (52 kg), 14 Toes-to-Bar'),
                                                    ('TOMMY', 'For Time', '21 Thrusters (43 kg), 12 Rope Climbs, 15 Thrusters (43 kg), 9 Rope Climbs, 9 Thrusters (43 kg), 6 Rope Climbs'),
                                                    ('TREVOR', 'For Time (Team of Four)', '300 Pull-Ups, 400 Push-Ups, 500 Sit-Ups, 600 Air Squats; Only two athletes can work at a time.'),
                                                    ('TULLY', '4 Rounds for Time', '200-meter Swim, 23 Wall Ball Shots (9 kg), 23 Kettlebell Swings (24 kg), 23 Pull-Ups, 23 Burpees'),
                                                    ('TYLER', '5 Rounds for Time', '7 Muscle-Ups, 21 Sumo Deadlift High-Pulls (43 kg)'),
                                                    ('WALKER', 'For Time', '4 Rounds: 800-meter Run, 400-meter Run with 20-kg plate'),
                                                    ('WALLACE', 'For Time', '3 Rounds: 21 Deadlifts (102 kg), 15 Pull-Ups, 9 Overhead Squats (43 kg)'),
                                                    ('WELSH', 'For Time', '5 Rounds: 200-meter Run, 10 Overhead Squats (43 kg), 10 Box Jumps (61 cm)'),
                                                    ('WHITE', '5 Rounds for Time', '3 Rope Climbs (4.5 m), 10 Toes-to-Bar, 21 Walking Lunges with 32 kg kettlebell'),
                                                    ('WILSON', 'For Time', '30 Kettlebell Swings (32 kg), 30 Box Jumps (61 cm), 30 Overhead Squats (43 kg)'),
                                                    ('WOOD', '5 Rounds for Time', '400-meter Run, 10 Burpee Box Jumps (61 cm), 10 Sumo Deadlift High-Pulls (43 kg), 10 Thrusters (43 kg), Rest 1 minute'),
                                                    ('WOODROW', 'For Time', '5 Rounds: 400-meter Run, 10 Burpee Box Jumps (61 cm), 10 Sumo Deadlift High-Pulls (43 kg), 10 Thrusters (43 kg), Rest 1 minute');
